image: docker:24.0.5
services:
  - docker:24.0.5-dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  DOCKER_TLS_CERTDIR: '/certs'

stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build .

build:
  stage: push
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        TAG="$CI_COMMIT_TAG"
      elif [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        TAG=latest
      else
        TAG=branch--$(echo $CI_COMMIT_REF_NAME | sed -e 's|/|--|g')
      fi
    - docker build -t "$CI_REGISTRY_IMAGE:$TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$TAG"
  rules:
    - if: "$CI_COMMIT_TAG || $W4_RELEASE"
